# Site settings
title: Yondon Fu
email: yondon.fu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just going at it one day at a time
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yondonfu.me" # the base hostname & protocol for your site
twitter_username: yondonfu
github_username:  yondonfu

# Build settings
markdown: kramdown
