# Site settings
title: Yondon Fu
email: Yondon.Fu.17@dartmouth.edu
description: > # this means to ignore newlines until "baseurl:"
  Dartmouth '17. NH-NYC-SF
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yondonfu.me" # the base hostname & protocol for your site
twitter_username: yondonfu
github_username:  yondonfu

# Build settings
markdown: kramdown
